# AnalyzerSingleton settings
analysis:
  model: EP #( E, P, EP )
  nbest: 5 #( 1 ~ 10 )
  tagging: true
  userdict: true
  converthanja: true
  decompond : false # 복합명사 분해 옵션

log:
  level: info #(info, warn, error)
  path: ./log

knowledge:
  system: ./wisekmapy/knowledge/wkb_nocomp.klg
  # compression: true # default false  # 시스템 사전 압축 여부
  usernoun: ./wisekmapy/knowledge/usernoun.txt
  encoding: utf8

license:
  path: ./wisekmapy/knowledge/license.xml
